### ISSUE TITLE
Transform collision-prevention to optional feature

### ISSUE THREAD

**Issue by marentschler** [GFragniere/CarGame#1]
Sometimes a user wants to disable the anti-collision help, since he thinks that there might be a way how to get through and that the algorithm was wrong. There could be a key to disable that check to be able to make a given move anyway, although the algorithm predicts a crash.

**Comment by GFragniere** [comment]
Very interesting idea indeed, I'll work on it!

**Comment by GFragniere** [comment]
All done and working!
